### Create a new category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Games",
  "description": "Devices and gadgets"
}

### Get all categories
GET http://localhost:3000/api/categories

### Get a category by ID
GET http://localhost:3000/api/categories/3

### Update a category
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
  "name": "Updated Electronics",
  "description": "Updated description"
}

### Delete a category
DELETE http://localhost:3000/api/categories/1